###USER CREATE
POST http://localhost:3000/users.json
Content-Type: application/json

{
"name": "Marc",
"email": "marc@info.com",
"password_digest": "password3",
"image": "image.png"
}

###TWEET CREATE
POST http://localhost:3000/tweets.json
Content-Type: application/json

{
  "user_id": 1,
  "text": "Marc has been banished to the land of forgotten Marcs.",
  "image": "image.url"
}

###Tweeter Deleter
DELETE http://lcoalhost:3000/tweets/1.json